version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=linux
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    # networks:
    #   - rust-network
  
  # rust-server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   entrypoint: ["/bin/sh","-c","(sqlx migrate run || echo 'ignoring migration') && ./target/release/server"]
  #   environment:
  #     DATABASE_URL: "postgres://postgres:linux@db:5432/mydatabase"
  #     HOST: "0.0.0.0"
  #     PORT: "8080"
  #     JWT_KEY: "SECRET_KEY"
  #     RUST_LOG: "actix_web=info"
  #   depends_on:
  #     - db
  #   networks:
  #     - rust-network

# networks:
#   rust-network:
#     driver: bridge